// Auto-generated PROGMEM arrays for embedded web files
// Do not edit manually - regenerate when web files change

#pragma once
#include <pgmspace.h>
// index.html (17710 bytes)
const char INDEX_HTML[] PROGMEM =
"<!DOCTYPE html>\n"
"<html lang=\"id\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=5.0\">\n"
"  <title>P10 IoT Matrix Controller</title>\n"
"  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Chakra+Petch:wght@600;700&display=swap\" rel=\"stylesheet\">\n"
"  <link rel=\"stylesheet\" href=\"style.css\">\n"
"</head>\n"
"<body>\n"
"\n"
"<div class=\"app-layout\">\n"
"\n"
"  <!-- SIDEBAR -->\n"
"  <aside class=\"app-sidebar\" id=\"appSidebar\">\n"
"    <div class=\"sidebar-header\">\n"
"      <div class=\"brand-badge\">\n"
"        <div class=\"brand-icon\">\n"
"          <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"            <rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"3\"/>\n"
"            <path d=\"M6 10h.01M10 10h.01M14 10h.01M18 10h.01M6 14h.01M10 14h.01M14 14h.01M18 14h.01\"/>\n"
"          </svg>\n"
"        </div>\n"
"        <div>\n"
"          <h1 class=\"brand-title\">P10 MATRIX</h1>\n"
"          <span class=\"brand-tag\">IoT Controller</span>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <nav class=\"sidebar-nav\">\n"
"      <button class=\"nav-item active\" data-tab=\"dashboard\" id=\"navDashboard\">\n"
"        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"          <rect x=\"3\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"14\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/>\n"
"          <rect x=\"14\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.5\"/>\n"
"        </svg>\n"
"        <span>Dashboard</span>\n"
"      </button>\n"
"      <button class=\"nav-item\" data-tab=\"perangkat\" id=\"navPerangkat\">\n"
"        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"          <rect x=\"2\" y=\"2\" width=\"20\" height=\"8\" rx=\"2\" ry=\"2\"/>\n"
"          <rect x=\"2\" y=\"14\" width=\"20\" height=\"8\" rx=\"2\" ry=\"2\"/>\n"
"          <line x1=\"6\" y1=\"6\" x2=\"6.01\" y2=\"6\"/><line x1=\"6\" y1=\"18\" x2=\"6.01\" y2=\"18\"/>\n"
"        </svg>\n"
"        <span>Perangkat</span>\n"
"      </button>\n"
"      <button class=\"nav-item\" data-tab=\"panduan\" id=\"navPanduan\">\n"
"        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"          <path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"/>\n"
"          <path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"/>\n"
"        </svg>\n"
"        <span>Panduan</span>\n"
"      </button>\n"
"    </nav>\n"
"\n"
"    <div class=\"sidebar-footer\">\n"
"      <div class=\"device-status-pill\">\n"
"        <span class=\"status-dot\"></span>\n"
"        <span class=\"status-label\" id=\"badgeText\">ESP8266 &bull; 192.168.4.1</span>\n"
"      </div>\n"
"      <button class=\"btn-sidebar-sync\" id=\"btnQuickSyncHeader\" title=\"Sinkronkan Waktu Browser ke ESP8266\">\n"
"        <svg viewBox=\"0 0 24 24\" width=\"13\" height=\"13\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"          <path d=\"M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67\"/>\n"
"        </svg>\n"
"        <span>Sync Waktu HP</span>\n"
"      </button>\n"
"    </div>\n"
"  </aside>\n"
"\n"
"  <!-- MAIN CONTENT -->\n"
"  <main class=\"app-main\">\n"
"\n"
"    <!-- DASHBOARD -->\n"
"    <section class=\"tab-content active\" id=\"tabContentDashboard\">\n"
"      <header class=\"page-header\">\n"
"        <h2 class=\"page-title\">Dashboard</h2>\n"
"        <button class=\"btn-header-action\" id=\"btnOpenSettingsModal\" title=\"Lihat JSON Payload\">\n"
"          <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"            <circle cx=\"12\" cy=\"12\" r=\"3\"/>\n"
"            <path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z\"/>\n"
"          </svg>\n"
"          <span>API</span>\n"
"        </button>\n"
"      </header>\n"
"\n"
"      <!-- SIMULATOR HERO -->\n"
"      <div class=\"simulator-card\">\n"
"        <div class=\"sim-header\">\n"
"          <button class=\"sim-mode-badge\" id=\"btnToggleSimMode\">\n"
"            <span class=\"live-dot\"></span>\n"
"            <span id=\"simModeLabel\">Mode: Jam</span>\n"
"          </button>\n"
"          <div class=\"color-dots\">\n"
"            <button class=\"color-dot red active\" data-color=\"red\" aria-label=\"Merah\"></button>\n"
"            <button class=\"color-dot cyan\" data-color=\"cyan\" aria-label=\"Cyan\"></button>\n"
"            <button class=\"color-dot green\" data-color=\"green\" aria-label=\"Hijau\"></button>\n"
"            <button class=\"color-dot amber\" data-color=\"amber\" aria-label=\"Amber\"></button>\n"
"            <button class=\"color-dot purple\" data-color=\"purple\" aria-label=\"Ungu\"></button>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"p10-screen\">\n"
"          <div class=\"p10-matrix theme-red\" id=\"p10Matrix\">\n"
"            <div class=\"matrix-layer\" id=\"matrixLayer\">\n"
"              <div class=\"matrix-clock\" id=\"matrixClockView\">\n"
"                <div class=\"p10-time-layout\">\n"
"                  <div class=\"p10-hours\" id=\"simHours\">12</div>\n"
"                  <div class=\"p10-colon blink\">:</div>\n"
"                  <div class=\"p10-min\" id=\"simMin\">45</div>\n"
"                </div>\n"
"                <div class=\"p10-date\" id=\"simDate\"></div>\n"
"              </div>\n"
"              <div class=\"matrix-marquee hidden\" id=\"matrixMarqueeView\">\n"
"                <div class=\"marquee-text scroll-left\" id=\"simMarqueeContent\">SELAMAT DATANG DI SISTEM IoT P10 ESP8266</div>\n"
"              </div>\n"
"            </div>\n"
"            <div class=\"dot-grid\"></div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"sim-meta\">\n"
"          <span id=\"simStatusInfo\">Scroll Kiri &bull; Speed Lv 5 &bull; Terang 80%</span>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- ACCORDION CONTROLS -->\n"
"      <div class=\"accordion\">\n"
"        <!-- Pesan Teks -->\n"
"        <div class=\"accordion-section\" data-section=\"pesan\">\n"
"          <div class=\"accordion-header\" onclick=\"toggleAccordion(this)\">\n"
"            <h3>Pesan Teks</h3>\n"
"            <svg class=\"accordion-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"              <polyline points=\"6 9 12 15 18 9\"/>\n"
"            </svg>\n"
"          </div>\n"
"          <div class=\"accordion-body\">\n"
"            <div class=\"form-group\">\n"
"              <div class=\"form-label\">\n"
"                <label for=\"inputText1\">Isi Pesan</label>\n"
"                <span class=\"form-value\" id=\"charCount1\">0/150</span>\n"
"              </div>\n"
"              <div class=\"input-wrap\">\n"
"                <input type=\"text\" id=\"inputText1\" class=\"form-input\" placeholder=\"Tulis pesan...\" maxlength=\"150\" value=\"SELAMAT DATANG DI SISTEM IoT P10 ESP8266\">\n"
"                <button class=\"btn-clear\" data-target=\"inputText1\">&times;</button>\n"
"              </div>\n"
"            </div>\n"
"            <div class=\"chips-row\">\n"
"              <button class=\"chip\" data-text=\"SELAMAT DATANG\">Selamat Datang</button>\n"
"              <button class=\"chip\" data-text=\"JAGALAH KEBERSIHAN & KETERTIBAN\">Kebersihan</button>\n"
"              <button class=\"chip\" data-text=\"WAKTU SHOLAT TELAH TIBA\">Waktu Sholat</button>\n"
"              <button class=\"chip\" data-text=\"TOKO BUKA - SILAKAN MASUK\">Toko Buka</button>\n"
"              <button class=\"chip\" data-text=\"INFO: PARKIR KHUSUS PENGUNJUNG\">Info Parkir</button>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Animasi & Durasi -->\n"
"        <div class=\"accordion-section\" data-section=\"animasi\">\n"
"          <div class=\"accordion-header\" onclick=\"toggleAccordion(this)\">\n"
"            <h3>Animasi & Durasi</h3>\n"
"            <svg class=\"accordion-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"              <polyline points=\"6 9 12 15 18 9\"/>\n"
"            </svg>\n"
"          </div>\n"
"          <div class=\"accordion-body\">\n"
"            <div class=\"segmented\">\n"
"              <button class=\"seg-btn active\" data-mode=\"cycle\">Bergantian</button>\n"
"              <button class=\"seg-btn\" data-mode=\"clock_only\">Jam Saja</button>\n"
"              <button class=\"seg-btn\" data-mode=\"text_only\">Teks Saja</button>\n"
"            </div>\n"
"\n"
"            <div class=\"anim-options\">\n"
"              <label class=\"anim-option active\">\n"
"                <input type=\"radio\" name=\"animEffect\" value=\"scroll_left\" checked>\n"
"                <div class=\"anim-content\">\n"
"                  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"/><polyline points=\"12 19 5 12 12 5\"/></svg>\n"
"                  <span>Scroll Kiri</span>\n"
"                </div>\n"
"              </label>\n"
"              <label class=\"anim-option\">\n"
"                <input type=\"radio\" name=\"animEffect\" value=\"scroll_right\">\n"
"                <div class=\"anim-content\">\n"
"                  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"/><polyline points=\"12 5 19 12 12 19\"/></svg>\n"
"                  <span>Scroll Kanan</span>\n"
"                </div>\n"
"              </label>\n"
"              <label class=\"anim-option\">\n"
"                <input type=\"radio\" name=\"animEffect\" value=\"static\">\n"
"                <div class=\"anim-content\">\n"
"                  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/></svg>\n"
"                  <span>Diam</span>\n"
"                </div>\n"
"              </label>\n"
"            </div>\n"
"\n"
"            <div class=\"form-group\">\n"
"              <div class=\"form-label\">\n"
"                <label for=\"speedSlider\">Kecepatan</label>\n"
"                <span class=\"form-value\" id=\"speedValueDisplay\">Level 5</span>\n"
"              </div>\n"
"              <input type=\"range\" id=\"speedSlider\" min=\"1\" max=\"10\" value=\"5\" class=\"app-range\">\n"
"            </div>\n"
"\n"
"            <div class=\"form-group\">\n"
"              <div class=\"form-label\">\n"
"                <label for=\"clockDuration\">Durasi Jam</label>\n"
"                <span class=\"form-value\" id=\"clockDurationDisplay\">10s</span>\n"
"              </div>\n"
"              <input type=\"range\" id=\"clockDuration\" min=\"3\" max=\"60\" value=\"10\" class=\"app-range\">\n"
"            </div>\n"
"\n"
"            <div class=\"form-group\">\n"
"              <div class=\"form-label\">\n"
"                <label for=\"textDuration\">Durasi Teks</label>\n"
"                <span class=\"form-value\" id=\"textDurationDisplay\">8s</span>\n"
"              </div>\n"
"              <input type=\"range\" id=\"textDuration\" min=\"3\" max=\"60\" value=\"8\" class=\"app-range\">\n"
"            </div>\n"
"\n"
"            <button class=\"btn-block\" id=\"btnQuickSyncCard\" title=\"Sinkronkan Waktu Browser ke ESP8266\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"13\" height=\"13\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"                <path d=\"M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67\"/>\n"
"              </svg>\n"
"              <span>Sync Waktu HP ke Panel</span>\n"
"            </button>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Kecerahan -->\n"
"        <div class=\"accordion-section\" data-section=\"kecerahan\">\n"
"          <div class=\"accordion-header\" onclick=\"toggleAccordion(this)\">\n"
"            <h3>Kecerahan</h3>\n"
"            <svg class=\"accordion-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"              <polyline points=\"6 9 12 15 18 9\"/>\n"
"            </svg>\n"
"          </div>\n"
"          <div class=\"accordion-body\">\n"
"            <div class=\"form-group\">\n"
"              <div class=\"form-label\">\n"
"                <label for=\"brightnessSlider\">Kecerahan LED</label>\n"
"                <span class=\"form-value\" id=\"brightnessValueDisplay\">80%</span>\n"
"              </div>\n"
"              <input type=\"range\" id=\"brightnessSlider\" min=\"5\" max=\"100\" value=\"80\" class=\"app-range\">\n"
"            </div>\n"
"            <div class=\"toggle-row\">\n"
"              <span class=\"toggle-title\">Mode Malam</span>\n"
"              <label class=\"switch\">\n"
"                <input type=\"checkbox\" id=\"toggleAutoDimming\">\n"
"                <span class=\"switch-slider\"></span>\n"
"              </label>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"    </section>\n"
"\n"
"    <!-- PERANGKAT -->\n"
"    <section class=\"tab-content\" id=\"tabContentPerangkat\">\n"
"      <header class=\"page-header\">\n"
"        <h2 class=\"page-title\">Perangkat</h2>\n"
"      </header>\n"
"\n"
"      <div class=\"info-card\">\n"
"        <h3>Koneksi</h3>\n"
"        <div class=\"form-group mb-2\">\n"
"          <label for=\"espIpInput\" class=\"form-label\">Alamat IP ESP8266</label>\n"
"          <div class=\"input-wrap\">\n"
"            <input type=\"text\" id=\"espIpInput\" class=\"form-input\" value=\"192.168.4.1\" placeholder=\"192.168.4.1\">\n"
"          </div>\n"
"        </div>\n"
"        <div class=\"info-list\">\n"
"          <div class=\"info-item\">\n"
"            <span class=\"info-key\">SSID Wi-Fi AP:</span>\n"
"            <span class=\"info-val\">P10_CLOCK_IOT</span>\n"
"          </div>\n"
"          <div class=\"info-item\">\n"
"            <span class=\"info-key\">Password:</span>\n"
"            <span class=\"info-val\">12345678</span>\n"
"          </div>\n"
"          <div class=\"info-item\">\n"
"            <span class=\"info-key\">Port:</span>\n"
"            <span class=\"info-val\">80 (HTTP)</span>\n"
"          </div>\n"
"        </div>\n"
"        <button class=\"btn-block\" id=\"btnTestPing\">Uji Koneksi ESP8266</button>\n"
"      </div>\n"
"\n"
"      <div class=\"info-card\" style=\"margin-top: 1rem;\">\n"
"        <h3>Data JSON</h3>\n"
"        <div class=\"json-box\">\n"
"          <div class=\"json-header\">\n"
"            <span>Payload Aktif</span>\n"
"            <button class=\"btn-copy\" id=\"btnCopyJson\">Salin</button>\n"
"          </div>\n"
"          <pre class=\"json-code\" id=\"jsonPayloadPreview\"></pre>\n"
"        </div>\n"
"        <button class=\"btn-send\" id=\"btnSendFromModal\" style=\"margin-top: 0.75rem;\">\n"
"          <svg viewBox=\"0 0 24 24\" width=\"15\" height=\"15\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"            <line x1=\"22\" y1=\"2\" x2=\"11\" y2=\"13\"/><polygon points=\"22 2 15 22 11 13 2 9 22 2\"/>\n"
"          </svg>\n"
"          <span>Kirim JSON Sekarang</span>\n"
"        </button>\n"
"      </div>\n"
"    </section>\n"
"\n"
"    <!-- PANDUAN -->\n"
"    <section class=\"tab-content\" id=\"tabContentPanduan\">\n"
"      <header class=\"page-header\">\n"
"        <h2 class=\"page-title\">Panduan</h2>\n"
"      </header>\n"
"\n"
"      <div class=\"info-card\">\n"
"        <h3>Pinout HUB12 (P10)</h3>\n"
"        <div class=\"table-wrap\">\n"
"          <table>\n"
"            <thead>\n"
"              <tr><th>ESP8266</th><th>Panel P10</th><th>Fungsi</th></tr>\n"
"            </thead>\n"
"            <tbody>\n"
"              <tr><td><code>D0 (GPIO16)</code></td><td><span class=\"pin-badge\">A</span></td><td>Address A</td></tr>\n"
"              <tr><td><code>D6 (GPIO12)</code></td><td><span class=\"pin-badge\">B</span></td><td>Address B</td></tr>\n"
"              <tr><td><code>D5 (GPIO14)</code></td><td><span class=\"pin-badge\">CLK</span></td><td>Clock</td></tr>\n"
"              <tr><td><code>D7 (GPIO13)</code></td><td><span class=\"pin-badge\">R (DATA)</span></td><td>Data In</td></tr>\n"
"              <tr><td><code>D8 (GPIO15)</code></td><td><span class=\"pin-badge\">OE</span></td><td>Brightness PWM</td></tr>\n"
"              <tr><td><code>D4 (GPIO2)</code></td><td><span class=\"pin-badge\">LAT</span></td><td>Latch Strobe</td></tr>\n"
"              <tr><td><code>GND</code></td><td><span class=\"pin-badge\">GND</span></td><td>Ground</td></tr>\n"
"            </tbody>\n"
"          </table>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"info-card\" style=\"margin-top: 1rem;\">\n"
"        <h3>Langkah Penggunaan</h3>\n"
"        <ol class=\"steps\">\n"
"          <li><strong>Power Supply:</strong> Gunakan adaptor 5V (3A-5A) ke terminal power P10. Jangan dari ESP8266.</li>\n"
"          <li><strong>Wi-Fi:</strong> Sambung ke <code>P10_CLOCK_IOT</code> (password: <code>12345678</code>).</li>\n"
"          <li><strong>Buka Browser:</strong> Akses <code>http://192.168.4.1</code>.</li>\n"
"          <li><strong>Sync Waktu:</strong> Klik tombol <em>Sync Waktu HP</em> untuk sinkronisasi jam.</li>\n"
"        </ol>\n"
"      </div>\n"
"    </section>\n"
"\n"
"  </main>\n"
"\n"
"  <!-- FLOATING BAR -->\n"
"  <div class=\"bottom-bar\">\n"
"    <div class=\"action-inner\">\n"
"      <button class=\"btn-send\" id=\"btnSendToESP\">\n"
"        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"          <line x1=\"22\" y1=\"2\" x2=\"11\" y2=\"13\"/><polygon points=\"22 2 15 22 11 13 2 9 22 2\"/>\n"
"        </svg>\n"
"        <span>KIRIM KE PANEL P10</span>\n"
"      </button>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- MODAL -->\n"
"  <div class=\"modal-overlay hidden\" id=\"payloadModal\">\n"
"    <div class=\"modal-card\">\n"
"      <div class=\"modal-header\">\n"
"        <h3 class=\"modal-title\">JSON Payload</h3>\n"
"        <button class=\"modal-close\" id=\"btnCloseModal\">&times;</button>\n"
"      </div>\n"
"      <div class=\"modal-body\">\n"
"        <pre class=\"json-code\" id=\"jsonPayloadModalPreview\"></pre>\n"
"      </div>\n"
"      <div class=\"modal-footer\">\n"
"        <button class=\"btn-subtle\" id=\"btnDismissModal\">Tutup</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- TOAST -->\n"
"  <div class=\"toast-shelf\" id=\"toastContainer\"></div>\n"
"\n"
"</div>\n"
"\n"
"<script src=\"app.js\"></script>\n"
"</body>\n"
"</html>\n"
;
const int INDEX_HTML_LEN = sizeof(INDEX_HTML) - 1;
const char INDEX_HTML_TYPE[] = "text/html";

// style.css (23756 bytes)
const char STYLE_CSS[] PROGMEM =
"/* ==========================================================================\n"
"   P10 IoT MATRIX CONTROLLER - ULTRA MINIMAL EMERALD\n"
"   Flat design, minimal effects, clean whitespace\n"
"   ========================================================================== */\n"
"\n"
":root {\n"
"  /* Backgrounds - Flat, no gradients */\n"
"  --bg-base: #0a0f0d;\n"
"  --bg-surface: #111916;\n"
"  --bg-elevated: #1a2420;\n"
"  --bg-hover: #1f2b26;\n"
"  --bg-input: #0d1210;\n"
"\n"
"  /* Borders - Subtle */\n"
"  --border: rgba(16, 185, 129, 0.1);\n"
"  --border-focus: rgba(16, 185, 129, 0.35);\n"
"\n"
"  /* Accent - Single emerald, no secondary */\n"
"  --accent: #10b981;\n"
"  --accent-light: #34d399;\n"
"  --accent-muted: rgba(16, 185, 129, 0.12);\n"
"\n"
"  /* Status */\n"
"  --green: #10b981;\n"
"  --red: #ef4444;\n"
"\n"
"  /* Text */\n"
"  --text: #f0fdf4;\n"
"  --text-muted: #a7f3d0;\n"
"  --text-dim: #6ee7b7;\n"
"\n"
"  /* Fonts */\n"
"  --font: 'Plus Jakarta Sans', -apple-system, sans-serif;\n"
"  --font-mono: 'Chakra Petch', monospace;\n"
"\n"
"  /* Sizing */\n"
"  --radius: 8px;\n"
"  --radius-lg: 12px;\n"
"}\n"
"\n"
"/* Reset */\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"\n"
"html, body {\n"
"  background: var(--bg-base);\n"
"  color: var(--text);\n"
"  font-family: var(--font);\n"
"  line-height: 1.5;\n"
"  min-height: 100vh;\n"
"}\n"
"\n"
"/* ==========================================================================\n"
"   LAYOUT\n"
"   ========================================================================== */\n"
".app-layout {\n"
"  display: flex;\n"
"  min-height: 100vh;\n"
"}\n"
"\n"
"/* Sidebar */\n"
".app-sidebar {\n"
"  position: fixed;\n"
"  top: 0; left: 0; bottom: 0;\n"
"  width: 220px;\n"
"  background: var(--bg-surface);\n"
"  border-right: 1px solid var(--border);\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: space-between;\n"
"  padding: 1.25rem 1rem;\n"
"  z-index: 90;\n"
"}\n"
"\n"
".sidebar-header { margin-bottom: 1.5rem; }\n"
"\n"
".brand-badge {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 0.6rem;\n"
"}\n"
"\n"
".brand-icon {\n"
"  width: 34px; height: 34px;\n"
"  border-radius: var(--radius);\n"
"  background: var(--accent-muted);\n"
"  border: 1px solid var(--border-focus);\n"
"  color: var(--accent-light);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"}\n"
"\n"
".brand-icon svg { width: 18px; height: 18px; }\n"
"\n"
".brand-title {\n"
"  font-size: 0.95rem;\n"
"  font-weight: 800;\n"
"  color: #fff;\n"
"}\n"
"\n"
".brand-tag {\n"
"  font-size: 0.65rem;\n"
"  font-weight: 600;\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
"/* Nav */\n"
".sidebar-nav {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 0.3rem;\n"
"  flex: 1;\n"
"}\n"
"\n"
".nav-item {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 0.65rem;\n"
"  background: transparent;\n"
"  border: 1px solid transparent;\n"
"  color: var(--text-muted);\n"
"  font-family: inherit;\n"
"  font-size: 0.82rem;\n"
"  font-weight: 600;\n"
"  padding: 0.6rem 0.8rem;\n"
"  border-radius: var(--radius);\n"
"  cursor: pointer;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".nav-item svg { width: 16px; height: 16px; flex-shrink: 0; }\n"
"\n"
".nav-item:hover {\n"
"  background: var(--bg-elevated);\n"
"  color: var(--text);\n"
"}\n"
"\n"
".nav-item.active {\n"
"  background: var(--accent-muted);\n"
"  border-color: var(--border-focus);\n"
"  color: #fff;\n"
"}\n"
"\n"
"/* Sidebar Footer */\n"
".sidebar-footer {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 0.5rem;\n"
"  padding-top: 0.75rem;\n"
"  border-top: 1px solid var(--border);\n"
"}\n"
"\n"
".device-status-pill {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 0.4rem;\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  padding: 0.35rem 0.6rem;\n"
"  border-radius: 999px;\n"
"}\n"
"\n"
".status-dot {\n"
"  width: 6px; height: 6px;\n"
"  border-radius: 50%;\n"
"  background: var(--green);\n"
"  box-shadow: 0 0 6px var(--green);\n"
"  animation: pulse 2s infinite ease-in-out;\n"
"}\n"
"\n"
"@keyframes pulse {\n"
"  0%, 100% { opacity: 1; }\n"
"  50% { opacity: 0.4; }\n"
"}\n"
"\n"
".status-label {\n"
"  font-size: 0.68rem;\n"
"  font-weight: 600;\n"
"  color: var(--text-muted);\n"
"}\n"
"\n"
".btn-sidebar-sync {\n"
"  width: 100%;\n"
"  background: var(--bg-elevated);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text);\n"
"  font-family: inherit;\n"
"  font-size: 0.72rem;\n"
"  font-weight: 600;\n"
"  padding: 0.45rem 0.7rem;\n"
"  border-radius: var(--radius);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  gap: 0.4rem;\n"
"  cursor: pointer;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".btn-sidebar-sync:hover {\n"
"  background: var(--accent-muted);\n"
"  border-color: var(--border-focus);\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
"/* ==========================================================================\n"
"   MAIN CONTENT\n"
"   ========================================================================== */\n"
".app-main {\n"
"  margin-left: 220px;\n"
"  flex: 1;\n"
"  min-width: 0;\n"
"  padding: 1.75rem 2rem 7rem;\n"
"}\n"
"\n"
".page-header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  margin-bottom: 1.25rem;\n"
"}\n"
"\n"
".page-title {\n"
"  font-size: 1.3rem;\n"
"  font-weight: 800;\n"
"  color: #fff;\n"
"}\n"
"\n"
".btn-header-action {\n"
"  background: var(--bg-surface);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text-muted);\n"
"  font-family: inherit;\n"
"  font-size: 0.72rem;\n"
"  font-weight: 600;\n"
"  padding: 0.4rem 0.65rem;\n"
"  border-radius: var(--radius);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 0.35rem;\n"
"  cursor: pointer;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".btn-header-action:hover {\n"
"  background: var(--bg-elevated);\n"
"  color: var(--text);\n"
"}\n"
"\n"
"/* Tab Content */\n"
".tab-content { display: none; }\n"
".tab-content.active { display: block; }\n"
"\n"
"/* ==========================================================================\n"
"   SIMULATOR HERO\n"
"   ========================================================================== */\n"
".simulator-card {\n"
"  background: var(--bg-surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius-lg);\n"
"  padding: 1rem;\n"
"  margin-bottom: 1rem;\n"
"}\n"
"\n"
".sim-header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  margin-bottom: 0.75rem;\n"
"}\n"
"\n"
".sim-mode-badge {\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text-muted);\n"
"  font-family: inherit;\n"
"  font-size: 0.68rem;\n"
"  font-weight: 600;\n"
"  padding: 0.25rem 0.55rem;\n"
"  border-radius: 999px;\n"
"  display: inline-flex;\n"
"  align-items: center;\n"
"  gap: 0.35rem;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".sim-mode-badge:hover {\n"
"  border-color: var(--border-focus);\n"
"  color: var(--text);\n"
"}\n"
"\n"
".live-dot {\n"
"  width: 6px; height: 6px;\n"
"  border-radius: 50%;\n"
"  background: var(--accent);\n"
"  box-shadow: 0 0 6px var(--accent);\n"
"  animation: pulse 1.5s infinite ease-in-out;\n"
"}\n"
"\n"
".color-dots {\n"
"  display: flex;\n"
"  gap: 0.35rem;\n"
"}\n"
"\n"
".color-dot {\n"
"  width: 14px; height: 14px;\n"
"  border-radius: 50%;\n"
"  border: 2px solid transparent;\n"
"  cursor: pointer;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".color-dot.red { background: #ff2a3b; }\n"
".color-dot.cyan { background: #00f0ff; }\n"
".color-dot.green { background: #10b981; }\n"
".color-dot.amber { background: #f59e0b; }\n"
".color-dot.purple { background: #a855f7; }\n"
"\n"
".color-dot.active {\n"
"  border-color: #fff;\n"
"  transform: scale(1.2);\n"
"}\n"
"\n"
"/* P10 Screen */\n"
".p10-screen {\n"
"  background: #05030a;\n"
"  border: 1px solid #1a1a2e;\n"
"  border-radius: var(--radius);\n"
"  overflow: hidden;\n"
"  height: 110px;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"}\n"
"\n"
".p10-matrix {\n"
"  width: 100%; height: 100%;\n"
"  position: relative;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  background: #05030a;\n"
"}\n"
"\n"
"/* Matrix themes - minimal glow only */\n"
".p10-matrix.theme-red { --m-color: #ff3344; --m-glow: 0 0 8px rgba(255,51,68,0.5); }\n"
".p10-matrix.theme-cyan { --m-color: #00f0ff; --m-glow: 0 0 8px rgba(0,240,255,0.5); }\n"
".p10-matrix.theme-green { --m-color: #10b981; --m-glow: 0 0 8px rgba(16,185,129,0.5); }\n"
".p10-matrix.theme-amber { --m-color: #f59e0b; --m-glow: 0 0 8px rgba(245,158,11,0.5); }\n"
".p10-matrix.theme-purple { --m-color: #c084fc; --m-glow: 0 0 8px rgba(192,132,252,0.5); }\n"
"\n"
".dot-grid {\n"
"  position: absolute;\n"
"  inset: 0;\n"
"  background-image: radial-gradient(circle, transparent 2px, rgba(0,0,0,0.5) 2.5px);\n"
"  background-size: 5px 5px;\n"
"  pointer-events: none;\n"
"  opacity: 0.3;\n"
"}\n"
"\n"
".matrix-layer {\n"
"  position: relative;\n"
"  z-index: 2;\n"
"  width: 100%; height: 100%;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  padding: 0 0.5rem;\n"
"}\n"
"\n"
".matrix-clock {\n"
"  text-align: center;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  gap: 2px;\n"
"}\n"
"\n"
".p10-time-layout {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  gap: 4px;\n"
"}\n"
"\n"
".p10-hours {\n"
"  font-family: var(--font-mono);\n"
"  font-size: 1.4rem;\n"
"  font-weight: 800;\n"
"  line-height: 1;\n"
"  color: var(--m-color);\n"
"  text-shadow: var(--m-glow);\n"
"}\n"
"\n"
".p10-colon {\n"
"  font-family: var(--font-mono);\n"
"  font-size: 1.4rem;\n"
"  font-weight: 800;\n"
"  line-height: 1;\n"
"  color: var(--m-color);\n"
"  text-shadow: var(--m-glow);\n"
"}\n"
"\n"
".p10-colon.blink {\n"
"  animation: colonBlink 1s step-end infinite;\n"
"}\n"
"\n"
"@keyframes colonBlink {\n"
"  0%, 100% { opacity: 1; }\n"
"  50% { opacity: 0.2; }\n"
"}\n"
"\n"
".p10-min {\n"
"  font-family: var(--font-mono);\n"
"  font-size: 1.4rem;\n"
"  font-weight: 800;\n"
"  line-height: 1;\n"
"  letter-spacing: 1px;\n"
"  color: var(--m-color);\n"
"  text-shadow: var(--m-glow);\n"
"}\n"
"\n"
".p10-date {\n"
"  font-family: var(--font-mono);\n"
"  font-size: 0.6rem;\n"
"  font-weight: 600;\n"
"  line-height: 1;\n"
"  letter-spacing: 1px;\n"
"  color: var(--m-color);\n"
"  text-shadow: var(--m-glow);\n"
"  opacity: 0.8;\n"
"}\n"
"\n"
"/* Marquee */\n"
".matrix-marquee {\n"
"  width: 100%; height: 100%;\n"
"  overflow: hidden;\n"
"  white-space: nowrap;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"}\n"
"\n"
".matrix-marquee.is-scroll { display: block; line-height: 90px; }\n"
"\n"
".marquee-text {\n"
"  display: inline-block;\n"
"  font-family: var(--font-mono);\n"
"  font-size: 1.6rem;\n"
"  font-weight: 800;\n"
"  letter-spacing: 2px;\n"
"  color: var(--m-color);\n"
"  text-shadow: var(--m-glow);\n"
"  vertical-align: middle;\n"
"}\n"
"\n"
"@keyframes scrollLeft { 0% { transform: translateX(100%); } 100% { transform: translateX(-100%); } }\n"
"@keyframes scrollRight { 0% { transform: translateX(-100%); } 100% { transform: translateX(100%); } }\n"
"\n"
".scroll-left { animation: scrollLeft 8s linear infinite; }\n"
".scroll-right { animation: scrollRight 8s linear infinite; }\n"
"\n"
".sim-meta {\n"
"  text-align: center;\n"
"  font-size: 0.68rem;\n"
"  color: var(--text-dim);\n"
"  margin-top: 0.5rem;\n"
"}\n"
"\n"
"/* ==========================================================================\n"
"   ACCORDION\n"
"   ========================================================================== */\n"
".accordion {\n"
"  background: var(--bg-surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius-lg);\n"
"  overflow: hidden;\n"
"  margin-bottom: 1rem;\n"
"}\n"
"\n"
".accordion-section + .accordion-section {\n"
"  border-top: 1px solid var(--border);\n"
"}\n"
"\n"
".accordion-header {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: space-between;\n"
"  padding: 0.85rem 1rem;\n"
"  cursor: pointer;\n"
"  user-select: none;\n"
"  transition: background 0.15s;\n"
"}\n"
"\n"
".accordion-header:hover {\n"
"  background: var(--bg-elevated);\n"
"}\n"
"\n"
".accordion-header h3 {\n"
"  font-size: 0.85rem;\n"
"  font-weight: 700;\n"
"  color: #fff;\n"
"}\n"
"\n"
".accordion-icon {\n"
"  width: 18px; height: 18px;\n"
"  color: var(--text-dim);\n"
"  transition: transform 0.2s;\n"
"}\n"
"\n"
".accordion-section.open .accordion-icon {\n"
"  transform: rotate(180deg);\n"
"}\n"
"\n"
".accordion-body {\n"
"  max-height: 0;\n"
"  overflow: hidden;\n"
"  transition: max-height 0.3s ease, padding 0.3s ease;\n"
"  padding: 0 1rem;\n"
"}\n"
"\n"
".accordion-section.open .accordion-body {\n"
"  max-height: 800px;\n"
"  padding: 0 1rem 1rem;\n"
"}\n"
"\n"
".accordion-body .form-group {\n"
"  margin-bottom: 0.75rem;\n"
"}\n"
"\n"
".accordion-body .form-group:last-child {\n"
"  margin-bottom: 0;\n"
"}\n"
"\n"
"/* ==========================================================================\n"
"   FORM CONTROLS\n"
"   ========================================================================== */\n"
".form-group {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 0.3rem;\n"
"}\n"
"\n"
".form-label {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  font-size: 0.75rem;\n"
"  font-weight: 600;\n"
"  color: var(--text-muted);\n"
"}\n"
"\n"
".form-value {\n"
"  font-size: 0.7rem;\n"
"  font-weight: 700;\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
".form-input {\n"
"  width: 100%;\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius);\n"
"  padding: 0.55rem 0.75rem;\n"
"  font-family: inherit;\n"
"  font-size: 0.82rem;\n"
"  color: #fff;\n"
"  outline: none;\n"
"  transition: border-color 0.15s;\n"
"}\n"
"\n"
".form-input:focus {\n"
"  border-color: var(--border-focus);\n"
"}\n"
"\n"
".input-wrap {\n"
"  position: relative;\n"
"  display: flex;\n"
"  align-items: center;\n"
"}\n"
"\n"
".input-wrap .form-input { padding-right: 2rem; }\n"
"\n"
".btn-clear {\n"
"  position: absolute;\n"
"  right: 0.4rem;\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: var(--text-dim);\n"
"  font-size: 1.1rem;\n"
"  cursor: pointer;\n"
"  padding: 0 0.3rem;\n"
"  line-height: 1;\n"
"}\n"
"\n"
".btn-clear:hover { color: var(--accent-light); }\n"
"\n"
"/* Range */\n"
".app-range {\n"
"  -webkit-appearance: none;\n"
"  width: 100%;\n"
"  height: 4px;\n"
"  border-radius: 999px;\n"
"  background: #1a2420;\n"
"  outline: none;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".app-range::-webkit-slider-thumb {\n"
"  -webkit-appearance: none;\n"
"  width: 16px; height: 16px;\n"
"  border-radius: 50%;\n"
"  background: var(--accent);\n"
"  border: 2px solid var(--bg-base);\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".app-range::-moz-range-thumb {\n"
"  width: 16px; height: 16px;\n"
"  border-radius: 50%;\n"
"  background: var(--accent);\n"
"  border: 2px solid var(--bg-base);\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Segmented */\n"
".segmented {\n"
"  display: flex;\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius);\n"
"  padding: 3px;\n"
"  gap: 3px;\n"
"}\n"
"\n"
".seg-btn {\n"
"  flex: 1;\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: var(--text-muted);\n"
"  font-family: inherit;\n"
"  font-size: 0.72rem;\n"
"  font-weight: 600;\n"
"  padding: 0.4rem 0.25rem;\n"
"  border-radius: 6px;\n"
"  cursor: pointer;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".seg-btn.active {\n"
"  background: var(--bg-elevated);\n"
"  color: #fff;\n"
"  border: 1px solid var(--border);\n"
"}\n"
"\n"
"/* Anim Options - 4 in a row */\n"
".anim-options {\n"
"  display: grid;\n"
"  grid-template-columns: repeat(4, 1fr);\n"
"  gap: 0.35rem;\n"
"}\n"
"\n"
".anim-option {\n"
"  position: relative;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".anim-option input { position: absolute; opacity: 0; }\n"
"\n"
".anim-content {\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius);\n"
"  padding: 0.45rem 0.2rem;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  align-items: center;\n"
"  gap: 0.2rem;\n"
"  font-size: 0.65rem;\n"
"  font-weight: 600;\n"
"  color: var(--text-muted);\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".anim-option input:checked + .anim-content {\n"
"  background: var(--accent-muted);\n"
"  border-color: var(--border-focus);\n"
"  color: #fff;\n"
"}\n"
"\n"
".anim-content svg { width: 14px; height: 14px; }\n"
"\n"
"/* Chips */\n"
".chips-row {\n"
"  display: flex;\n"
"  gap: 0.3rem;\n"
"  overflow-x: auto;\n"
"  scrollbar-width: none;\n"
"}\n"
"\n"
".chips-row::-webkit-scrollbar { display: none; }\n"
"\n"
".chip {\n"
"  background: var(--bg-elevated);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text-muted);\n"
"  font-family: inherit;\n"
"  font-size: 0.65rem;\n"
"  font-weight: 600;\n"
"  padding: 0.25rem 0.55rem;\n"
"  border-radius: 999px;\n"
"  cursor: pointer;\n"
"  white-space: nowrap;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".chip:hover {\n"
"  background: var(--accent-muted);\n"
"  border-color: var(--border-focus);\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
"/* Toggle */\n"
".toggle-row {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"}\n"
"\n"
".toggle-title {\n"
"  font-size: 0.78rem;\n"
"  font-weight: 600;\n"
"  color: var(--text);\n"
"}\n"
"\n"
".switch {\n"
"  position: relative;\n"
"  width: 38px; height: 20px;\n"
"  flex-shrink: 0;\n"
"}\n"
"\n"
".switch input { opacity: 0; width: 0; height: 0; }\n"
"\n"
".switch-slider {\n"
"  position: absolute;\n"
"  cursor: pointer;\n"
"  inset: 0;\n"
"  background: #1a2420;\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 999px;\n"
"  transition: 0.2s;\n"
"}\n"
"\n"
".switch-slider::before {\n"
"  content: \"\";\n"
"  position: absolute;\n"
"  height: 14px; width: 14px;\n"
"  left: 2px; bottom: 2px;\n"
"  background: #fff;\n"
"  border-radius: 50%;\n"
"  transition: 0.2s;\n"
"}\n"
"\n"
".switch input:checked + .switch-slider {\n"
"  background: var(--accent);\n"
"}\n"
"\n"
".switch input:checked + .switch-slider::before {\n"
"  transform: translateX(18px);\n"
"  background: var(--bg-base);\n"
"}\n"
"\n"
"/* ==========================================================================\n"
"   FLOATING ACTION BAR\n"
"   ========================================================================== */\n"
".bottom-bar {\n"
"  position: fixed;\n"
"  bottom: 0;\n"
"  left: 220px; right: 0;\n"
"  background: rgba(10, 15, 13, 0.95);\n"
"  backdrop-filter: blur(12px);\n"
"  border-top: 1px solid var(--border);\n"
"  padding: 0.6rem 2rem calc(0.6rem + env(safe-area-inset-bottom));\n"
"  z-index: 80;\n"
"}\n"
"\n"
".bottom-bar .action-inner {\n"
"  max-width: 100%;\n"
"}\n"
"\n"
".btn-send {\n"
"  width: 100%;\n"
"  background: var(--accent);\n"
"  color: #fff;\n"
"  border: none;\n"
"  font-family: inherit;\n"
"  font-size: 0.82rem;\n"
"  font-weight: 700;\n"
"  padding: 0.65rem 1.2rem;\n"
"  border-radius: var(--radius);\n"
"  cursor: pointer;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  gap: 0.45rem;\n"
"  transition: all 0.15s;\n"
"}\n"
"\n"
".btn-send:hover {\n"
"  background: var(--accent-light);\n"
"}\n"
"\n"
".btn-send svg { width: 15px; height: 15px; }\n"
"\n"
"/* ==========================================================================\n"
"   PERANGKAT & PANDUAN - SINGLE CARD\n"
"   ========================================================================== */\n"
".info-card {\n"
"  background: var(--bg-surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius-lg);\n"
"  padding: 1.25rem;\n"
"}\n"
"\n"
".info-card h3 {\n"
"  font-size: 0.9rem;\n"
"  font-weight: 700;\n"
"  color: #fff;\n"
"  margin-bottom: 0.75rem;\n"
"}\n"
"\n"
".info-list {\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius);\n"
"  padding: 0.6rem;\n"
"  margin-bottom: 0.75rem;\n"
"}\n"
"\n"
".info-item {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  font-size: 0.72rem;\n"
"  padding: 0.3rem 0;\n"
"}\n"
"\n"
".info-item + .info-item {\n"
"  border-top: 1px solid var(--border);\n"
"}\n"
"\n"
".info-key { color: var(--text-muted); }\n"
".info-val { color: #fff; font-weight: 600; font-family: var(--font-mono); }\n"
"\n"
".json-box {\n"
"  background: var(--bg-input);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: var(--radius);\n"
"  overflow: hidden;\n"
"}\n"
"\n"
".json-header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  padding: 0.4rem 0.6rem;\n"
"  background: var(--bg-elevated);\n"
"  border-bottom: 1px solid var(--border);\n"
"  font-size: 0.7rem;\n"
"  font-weight: 600;\n"
"  color: var(--text-muted);\n"
"}\n"
"\n"
".json-code {\n"
"  padding: 0.6rem;\n"
"  font-family: var(--font-mono);\n"
"  font-size: 0.7rem;\n"
"  color: var(--accent-light);\n"
"  max-height: 160px;\n"
"  overflow-y: auto;\n"
"  white-space: pre-wrap;\n"
"  word-break: break-all;\n"
"}\n"
"\n"
".table-wrap { overflow-x: auto; }\n"
"\n"
"table {\n"
"  width: 100%;\n"
"  border-collapse: collapse;\n"
"  font-size: 0.75rem;\n"
"}\n"
"\n"
"th {\n"
"  color: var(--text-muted);\n"
"  font-weight: 600;\n"
"  padding: 0.5rem 0.6rem;\n"
"  border-bottom: 1px solid var(--border);\n"
"  text-align: left;\n"
"}\n"
"\n"
"td {\n"
"  padding: 0.5rem 0.6rem;\n"
"  border-bottom: 1px solid var(--border);\n"
"  color: var(--text);\n"
"}\n"
"\n"
"code {\n"
"  background: var(--accent-muted);\n"
"  border: 1px solid var(--border-focus);\n"
"  padding: 0.1rem 0.25rem;\n"
"  border-radius: 4px;\n"
"  font-family: var(--font-mono);\n"
"  font-size: 0.8em;\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
".pin-badge {\n"
"  background: var(--accent-muted);\n"
"  border: 1px solid var(--border-focus);\n"
"  color: var(--accent-light);\n"
"  font-family: var(--font-mono);\n"
"  font-weight: 700;\n"
"  font-size: 0.68rem;\n"
"  padding: 0.1rem 0.3rem;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
".steps {\n"
"  padding-left: 1rem;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 0.5rem;\n"
"  font-size: 0.78rem;\n"
"  color: var(--text-muted);\n"
"}\n"
"\n"
".steps strong { color: var(--text); }\n"
"\n"
".btn-block {\n"
"  width: 100%;\n"
"  background: var(--bg-elevated);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text);\n"
"  font-family: inherit;\n"
"  font-size: 0.75rem;\n"
"  font-weight: 600;\n"
"  padding: 0.5rem 0.8rem;\n"
"  border-radius: var(--radius);\n"
"  cursor: pointer;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  gap: 0.4rem;\n"
"  transition: all 0.15s;\n"
"  margin-top: 0.75rem;\n"
"}\n"
"\n"
".btn-block:hover {\n"
"  background: var(--accent-muted);\n"
"  border-color: var(--border-focus);\n"
"  color: var(--accent-light);\n"
"}\n"
"\n"
".btn-copy {\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: var(--accent-light);\n"
"  font-family: inherit;\n"
"  font-size: 0.7rem;\n"
"  font-weight: 700;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".btn-copy:hover { text-decoration: underline; }\n"
"\n"
"/* ==========================================================================\n"
"   MODAL & TOAST\n"
"   ========================================================================== */\n"
".modal-overlay {\n"
"  position: fixed;\n"
"  inset: 0;\n"
"  background: rgba(0, 0, 0, 0.8);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  padding: 1rem;\n"
"  z-index: 200;\n"
"}\n"
"\n"
".modal-card {\n"
"  background: var(--bg-surface);\n"
"  border: 1px solid var(--border-focus);\n"
"  border-radius: var(--radius-lg);\n"
"  width: 100%;\n"
"  max-width: 420px;\n"
"}\n"
"\n"
".modal-header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  padding: 0.75rem 1rem;\n"
"  border-bottom: 1px solid var(--border);\n"
"}\n"
"\n"
".modal-title {\n"
"  font-size: 0.88rem;\n"
"  font-weight: 700;\n"
"  color: #fff;\n"
"}\n"
"\n"
".modal-close {\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: var(--text-dim);\n"
"  font-size: 1.2rem;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".modal-body { padding: 1rem; }\n"
".modal-footer {\n"
"  display: flex;\n"
"  justify-content: flex-end;\n"
"  padding: 0.6rem 1rem;\n"
"  border-top: 1px solid var(--border);\n"
"}\n"
"\n"
".btn-subtle {\n"
"  background: var(--bg-elevated);\n"
"  border: 1px solid var(--border);\n"
"  color: var(--text);\n"
"  font-family: inherit;\n"
"  font-size: 0.75rem;\n"
"  font-weight: 600;\n"
"  padding: 0.45rem 0.8rem;\n"
"  border-radius: var(--radius);\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".toast-shelf {\n"
"  position: fixed;\n"
"  top: 0.75rem;\n"
"  left: 50%;\n"
"  transform: translateX(-50%);\n"
"  z-index: 300;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 0.4rem;\n"
"  width: 90%;\n"
"  max-width: 340px;\n"
"  pointer-events: none;\n"
"}\n"
"\n"
".toast {\n"
"  background: var(--bg-elevated);\n"
"  border: 1px solid var(--border-focus);\n"
"  color: #fff;\n"
"  padding: 0.55rem 0.8rem;\n"
"  border-radius: var(--radius);\n"
"  font-size: 0.75rem;\n"
"  font-weight: 600;\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 0.45rem;\n"
"  pointer-events: auto;\n"
"  animation: slideDown 0.2s ease;\n"
"}\n"
"\n"
".toast.success { border-left: 3px solid var(--green); }\n"
".toast.error { border-left: 3px solid var(--red); }\n"
".toast.info { border-left: 3px solid var(--accent-light); }\n"
"\n"
"@keyframes slideDown {\n"
"  from { opacity: 0; transform: translateY(-8px); }\n"
"  to { opacity: 1; transform: translateY(0); }\n"
"}\n"
"\n"
".hidden { display: none !important; }\n"
".text-muted { color: var(--text-muted); }\n"
".mb-2 { margin-bottom: 0.4rem; }\n"
"\n"
"/* ==========================================================================\n"
"   RESPONSIVE\n"
"   ========================================================================== */\n"
"@media (max-width: 860px) {\n"
"  .app-sidebar {\n"
"    position: fixed;\n"
"    top: 0; left: 0; right: 0;\n"
"    bottom: auto;\n"
"    width: 100%;\n"
"    height: 52px;\n"
"    padding: 0 0.75rem;\n"
"    flex-direction: row;\n"
"    align-items: center;\n"
"    justify-content: space-between;\n"
"    background: rgba(10, 15, 13, 0.96);\n"
"    backdrop-filter: blur(12px);\n"
"    border-right: none;\n"
"    border-bottom: 1px solid var(--border);\n"
"  }\n"
"\n"
"  .sidebar-header { margin-bottom: 0; }\n"
"  .brand-icon { width: 30px; height: 30px; }\n"
"  .brand-icon svg { width: 16px; height: 16px; }\n"
"  .brand-title { font-size: 0.88rem; }\n"
"  .brand-tag { display: none; }\n"
"\n"
"  .sidebar-nav {\n"
"    flex-direction: row;\n"
"    gap: 0.25rem;\n"
"  }\n"
"\n"
"  .nav-item {\n"
"    padding: 0.4rem 0.6rem;\n"
"    font-size: 0.72rem;\n"
"    gap: 0.3rem;\n"
"    border-radius: 999px;\n"
"  }\n"
"\n"
"  .nav-item svg { width: 14px; height: 14px; }\n"
"  .sidebar-footer { display: none; }\n"
"\n"
"  .app-main {\n"
"    margin-left: 0;\n"
"    padding: 4.2rem 1rem 6rem;\n"
"  }\n"
"\n"
"  .bottom-bar { left: 0; padding: 0.5rem 1rem calc(0.5rem + env(safe-area-inset-bottom)); }\n"
"\n"
"  .p10-screen { height: 95px; }\n"
"  .p10-hours, .p10-min, .p10-colon { font-size: 1.2rem; }\n"
"  .p10-date { font-size: 0.55rem; }\n"
"  .matrix-marquee.is-scroll { line-height: 80px; }\n"
"  .marquee-text { font-size: 1.4rem; }\n"
"}\n"
"\n"
"@media (max-width: 460px) {\n"
"  .brand-title { font-size: 0.82rem; }\n"
"  .nav-item { padding: 0.35rem 0.5rem; font-size: 0.68rem; }\n"
"\n"
"  .anim-options { grid-template-columns: repeat(2, 1fr); }\n"
"  .anim-content { flex-direction: row; justify-content: center; }\n"
"}\n"
;
const int STYLE_CSS_LEN = sizeof(STYLE_CSS) - 1;
const char STYLE_CSS_TYPE[] = "text/css";

// app.js (18408 bytes)
const char APP_JS[] PROGMEM =
"/**\n"
" * P10 IoT Controller - Ultra Minimal Edition\n"
" */\n"
"\n"
"// State\n"
"const state = {\n"
"  text1: \"SELAMAT DATANG DI SISTEM IoT P10 ESP8266\",\n"
"  anim: \"scroll_left\",\n"
"  speed: 5,\n"
"  clockDuration: 10,\n"
"  textDuration: 8,\n"
"  displayMode: \"cycle\",\n"
"  brightness: 80,\n"
"  autoDimming: false,\n"
"  themeColor: \"red\",\n"
"  espIp: \"192.168.4.1\",\n"
"  simCurrentView: \"clock\",\n"
"  simTimer: null\n"
"};\n"
"\n"
"// DOM Elements\n"
"const el = {\n"
"  navItems: document.querySelectorAll('.nav-item'),\n"
"  tabContents: document.querySelectorAll('.tab-content'),\n"
"  p10Matrix: document.getElementById('p10Matrix'),\n"
"  matrixClockView: document.getElementById('matrixClockView'),\n"
"  matrixMarqueeView: document.getElementById('matrixMarqueeView'),\n"
"  simTimeDisplay: document.getElementById('simHours'),\n"
"  simMinDisplay: document.getElementById('simMin'),\n"
"  simDateDisplay: document.getElementById('simDate'),\n"
"  simMarqueeContent: document.getElementById('simMarqueeContent'),\n"
"  simStatusInfo: document.getElementById('simStatusInfo'),\n"
"  simModeLabel: document.getElementById('simModeLabel'),\n"
"  btnToggleSimMode: document.getElementById('btnToggleSimMode'),\n"
"  colorDots: document.querySelectorAll('.color-dot'),\n"
"  badgeText: document.getElementById('badgeText'),\n"
"  btnQuickSyncHeader: document.getElementById('btnQuickSyncHeader'),\n"
"  btnQuickSyncCard: document.getElementById('btnQuickSyncCard'),\n"
"  inputText1: document.getElementById('inputText1'),\n"
"  charCount1: document.getElementById('charCount1'),\n"
"  presetChips: document.querySelectorAll('.chip'),\n"
"  btnClearInputs: document.querySelectorAll('.btn-clear'),\n"
"  animRadios: document.querySelectorAll('input[name=\"animEffect\"]'),\n"
"  animOptions: document.querySelectorAll('.anim-option'),\n"
"  speedSlider: document.getElementById('speedSlider'),\n"
"  speedValueDisplay: document.getElementById('speedValueDisplay'),\n"
"  clockDuration: document.getElementById('clockDuration'),\n"
"  clockDurationDisplay: document.getElementById('clockDurationDisplay'),\n"
"  textDuration: document.getElementById('textDuration'),\n"
"  textDurationDisplay: document.getElementById('textDurationDisplay'),\n"
"  segBtns: document.querySelectorAll('.seg-btn'),\n"
"  brightnessSlider: document.getElementById('brightnessSlider'),\n"
"  brightnessValueDisplay: document.getElementById('brightnessValueDisplay'),\n"
"  toggleAutoDimming: document.getElementById('toggleAutoDimming'),\n"
"  btnSendToESP: document.getElementById('btnSendToESP'),\n"
"  btnSendFromModal: document.getElementById('btnSendFromModal'),\n"
"  espIpInput: document.getElementById('espIpInput'),\n"
"  btnTestPing: document.getElementById('btnTestPing'),\n"
"  toastContainer: document.getElementById('toastContainer'),\n"
"  jsonPayloadPreview: document.getElementById('jsonPayloadPreview'),\n"
"  jsonPayloadModalPreview: document.getElementById('jsonPayloadModalPreview'),\n"
"  btnCopyJson: document.getElementById('btnCopyJson'),\n"
"  payloadModal: document.getElementById('payloadModal'),\n"
"  btnOpenSettingsModal: document.getElementById('btnOpenSettingsModal'),\n"
"  btnCloseModal: document.getElementById('btnCloseModal'),\n"
"  btnDismissModal: document.getElementById('btnDismissModal')\n"
"};\n"
"\n"
"// Accordion Toggle (global)\n"
"window.toggleAccordion = function(header) {\n"
"  const section = header.parentElement;\n"
"  section.classList.toggle('open');\n"
"};\n"
"\n"
"// Init\n"
"document.addEventListener('DOMContentLoaded', () => {\n"
"  loadSavedSettings();\n"
"  initSimulatorTheme();\n"
"  setupNavigationTabs();\n"
"  setupEventListeners();\n"
"  startClockTicker();\n"
"  startSimulatorCycle();\n"
"  updateSimulatorUI();\n"
"  updateJsonPayloadPreviews();\n"
"});\n"
"\n"
"// Navigation\n"
"function setupNavigationTabs() {\n"
"  el.navItems.forEach(btn => {\n"
"    btn.addEventListener('click', () => {\n"
"      const tab = btn.dataset.tab;\n"
"      el.navItems.forEach(i => i.classList.remove('active'));\n"
"      btn.classList.add('active');\n"
"      el.tabContents.forEach(p => {\n"
"        p.classList.remove('active');\n"
"        if (p.id === `tabContent${capitalize(tab)}`) p.classList.add('active');\n"
"      });\n"
"      if (tab === 'perangkat') updateJsonPayloadPreviews();\n"
"      window.scrollTo({ top: 0, behavior: 'smooth' });\n"
"    });\n"
"  });\n"
"}\n"
"\n"
"function capitalize(s) { return s ? s.charAt(0).toUpperCase() + s.slice(1) : ''; }\n"
"\n"
"// Local Storage\n"
"function loadSavedSettings() {\n"
"  try {\n"
"    const saved = localStorage.getItem('p10_matrix_config');\n"
"    if (saved) {\n"
"      const p = JSON.parse(saved);\n"
"      Object.assign(state, p);\n"
"      if (state.anim === 'fade_out') state.anim = 'scroll_left';\n"
"      if (el.inputText1) el.inputText1.value = state.text1;\n"
"      if (el.speedSlider) el.speedSlider.value = state.speed;\n"
"      if (el.clockDuration) el.clockDuration.value = state.clockDuration;\n"
"      if (el.textDuration) el.textDuration.value = state.textDuration;\n"
"      if (el.brightnessSlider) el.brightnessSlider.value = state.brightness;\n"
"      if (el.toggleAutoDimming) el.toggleAutoDimming.checked = state.autoDimming;\n"
"      if (el.espIpInput) el.espIpInput.value = state.espIp || '192.168.4.1';\n"
"\n"
"      el.animRadios.forEach(radio => {\n"
"        const wrapper = radio.closest('.anim-option');\n"
"        if (radio.value === state.anim) {\n"
"          radio.checked = true;\n"
"          if (wrapper) wrapper.classList.add('active');\n"
"        } else {\n"
"          if (wrapper) wrapper.classList.remove('active');\n"
"        }\n"
"      });\n"
"\n"
"      el.segBtns.forEach(btn => {\n"
"        btn.classList.toggle('active', btn.dataset.mode === state.displayMode);\n"
"      });\n"
"    }\n"
"  } catch (e) {\n"
"    console.warn('Could not load settings', e);\n"
"  }\n"
"  updateCharCounts();\n"
"  updateBadgeLabels();\n"
"  if (el.badgeText) el.badgeText.textContent = `ESP8266 \\u2022 ${state.espIp || '192.168.4.1'}`;\n"
"}\n"
"\n"
"function saveSettings() {\n"
"  try {\n"
"    localStorage.setItem('p10_matrix_config', JSON.stringify(state));\n"
"    updateJsonPayloadPreviews();\n"
"  } catch (e) {\n"
"    console.warn('Could not save settings', e);\n"
"  }\n"
"}\n"
"\n"
"// Clock\n"
"function startClockTicker() {\n"
"  updateTimeDisplays();\n"
"  setInterval(updateTimeDisplays, 1000);\n"
"}\n"
"\n"
"function getFormattedTime(date = new Date()) {\n"
"  const h = String(date.getHours()).padStart(2, '0');\n"
"  const m = String(date.getMinutes()).padStart(2, '0');\n"
"  const s = String(date.getSeconds()).padStart(2, '0');\n"
"  return { hours: h, minutes: m, seconds: s };\n"
"}\n"
"\n"
"function getFormattedDate(date = new Date()) {\n"
"  const days = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'];\n"
"  return days[date.getDay()];\n"
"}\n"
"\n"
"function updateTimeDisplays() {\n"
"  const { hours, minutes } = getFormattedTime();\n"
"  if (state.simCurrentView === 'clock') {\n"
"    if (el.simTimeDisplay) el.simTimeDisplay.textContent = hours;\n"
"    if (el.simMinDisplay) el.simMinDisplay.textContent = minutes;\n"
"    if (el.simDateDisplay) el.simDateDisplay.textContent = getFormattedDate();\n"
"  }\n"
"}\n"
"\n"
"// Simulator\n"
"function initSimulatorTheme() {\n"
"  if (el.p10Matrix) el.p10Matrix.className = `p10-matrix theme-${state.themeColor}`;\n"
"  el.colorDots.forEach(d => d.classList.toggle('active', d.dataset.color === state.themeColor));\n"
"}\n"
"\n"
"function updateSimulatorUI() {\n"
"  if (!el.simMarqueeContent) return;\n"
"  el.simMarqueeContent.textContent = state.text1 || \"P10 ESP8266\";\n"
"  el.simMarqueeContent.className = 'marquee-text';\n"
"\n"
"  const dur = Math.max(2.5, 22 - (state.speed * 2.0));\n"
"  el.simMarqueeContent.style.animationDuration = `${dur}s`;\n"
"\n"
"  if (state.anim === 'scroll_left' || state.anim === 'scroll_right') {\n"
"    if (el.matrixMarqueeView) el.matrixMarqueeView.classList.add('is-scroll');\n"
"    el.simMarqueeContent.classList.add(state.anim === 'scroll_left' ? 'scroll-left' : 'scroll-right');\n"
"  } else {\n"
"    if (el.matrixMarqueeView) el.matrixMarqueeView.classList.remove('is-scroll');\n"
"  }\n"
"\n"
"  if (el.simStatusInfo) {\n"
"    const names = { scroll_left: 'Scroll Kiri', scroll_right: 'Scroll Kanan', static: 'Diam' };\n"
"    el.simStatusInfo.textContent = `${names[state.anim] || 'Scroll'} \\u2022 Speed Lv ${state.speed} \\u2022 Terang ${state.brightness}%`;\n"
"  }\n"
"}\n"
"\n"
"function startSimulatorCycle() {\n"
"  if (state.simTimer) clearTimeout(state.simTimer);\n"
"  if (state.displayMode === 'clock_only') { switchSimView('clock'); return; }\n"
"  if (state.displayMode === 'text_only') { switchSimView('marquee'); return; }\n"
"\n"
"  let isClock = true;\n"
"  switchSimView('clock');\n"
"\n"
"  function scheduleNext() {\n"
"    const delay = (isClock ? state.clockDuration : state.textDuration) * 1000;\n"
"    state.simTimer = setTimeout(() => {\n"
"      isClock = !isClock;\n"
"      if (!isClock) { updateSimulatorUI(); switchSimView('marquee'); }\n"
"      else { switchSimView('clock'); }\n"
"      scheduleNext();\n"
"    }, delay);\n"
"  }\n"
"  scheduleNext();\n"
"}\n"
"\n"
"function switchSimView(view) {\n"
"  state.simCurrentView = view;\n"
"  if (view === 'clock') {\n"
"    if (el.matrixClockView) el.matrixClockView.classList.remove('hidden');\n"
"    if (el.matrixMarqueeView) el.matrixMarqueeView.classList.add('hidden');\n"
"    if (el.simModeLabel) el.simModeLabel.textContent = \"Mode: Jam\";\n"
"    updateTimeDisplays();\n"
"  } else {\n"
"    if (el.matrixClockView) el.matrixClockView.classList.add('hidden');\n"
"    if (el.matrixMarqueeView) el.matrixMarqueeView.classList.remove('hidden');\n"
"    if (el.simModeLabel) el.simModeLabel.textContent = \"Mode: Teks\";\n"
"    updateSimulatorUI();\n"
"  }\n"
"}\n"
"\n"
"// Event Listeners\n"
"function setupEventListeners() {\n"
"  if (el.inputText1) {\n"
"    el.inputText1.addEventListener('input', (e) => {\n"
"      state.text1 = e.target.value;\n"
"      updateCharCounts();\n"
"      updateSimulatorUI();\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  el.btnClearInputs.forEach(btn => {\n"
"    btn.addEventListener('click', () => {\n"
"      const input = document.getElementById(btn.dataset.target);\n"
"      if (input) { input.value = ''; input.dispatchEvent(new Event('input')); }\n"
"    });\n"
"  });\n"
"\n"
"  el.presetChips.forEach(chip => {\n"
"    chip.addEventListener('click', () => {\n"
"      if (el.inputText1) {\n"
"        el.inputText1.value = chip.dataset.text;\n"
"        el.inputText1.dispatchEvent(new Event('input'));\n"
"        showToast(`Template \"${chip.textContent}\" diterapkan!`, 'info');\n"
"      }\n"
"    });\n"
"  });\n"
"\n"
"  el.animRadios.forEach(radio => {\n"
"    radio.addEventListener('change', (e) => {\n"
"      if (e.target.checked) {\n"
"        state.anim = e.target.value;\n"
"        el.animOptions.forEach(o => o.classList.remove('active'));\n"
"        const wrapper = e.target.closest('.anim-option');\n"
"        if (wrapper) wrapper.classList.add('active');\n"
"        updateSimulatorUI();\n"
"        saveSettings();\n"
"      }\n"
"    });\n"
"  });\n"
"\n"
"  if (el.speedSlider) {\n"
"    el.speedSlider.addEventListener('input', (e) => {\n"
"      state.speed = parseInt(e.target.value, 10);\n"
"      updateBadgeLabels();\n"
"      updateSimulatorUI();\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  if (el.clockDuration) {\n"
"    el.clockDuration.addEventListener('input', (e) => {\n"
"      state.clockDuration = parseInt(e.target.value, 10);\n"
"      updateBadgeLabels();\n"
"      startSimulatorCycle();\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  if (el.textDuration) {\n"
"    el.textDuration.addEventListener('input', (e) => {\n"
"      state.textDuration = parseInt(e.target.value, 10);\n"
"      updateBadgeLabels();\n"
"      startSimulatorCycle();\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  el.segBtns.forEach(btn => {\n"
"    btn.addEventListener('click', () => {\n"
"      el.segBtns.forEach(b => b.classList.remove('active'));\n"
"      btn.classList.add('active');\n"
"      state.displayMode = btn.dataset.mode;\n"
"      startSimulatorCycle();\n"
"      saveSettings();\n"
"    });\n"
"  });\n"
"\n"
"  if (el.brightnessSlider) {\n"
"    el.brightnessSlider.addEventListener('input', (e) => {\n"
"      state.brightness = parseInt(e.target.value, 10);\n"
"      updateBadgeLabels();\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  if (el.toggleAutoDimming) {\n"
"    el.toggleAutoDimming.addEventListener('change', (e) => {\n"
"      state.autoDimming = e.target.checked;\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  el.colorDots.forEach(dot => {\n"
"    dot.addEventListener('click', () => {\n"
"      state.themeColor = dot.dataset.color;\n"
"      initSimulatorTheme();\n"
"      saveSettings();\n"
"    });\n"
"  });\n"
"\n"
"  if (el.btnToggleSimMode) {\n"
"    el.btnToggleSimMode.addEventListener('click', () => {\n"
"      switchSimView(state.simCurrentView === 'clock' ? 'marquee' : 'clock');\n"
"    });\n"
"  }\n"
"\n"
"  if (el.btnQuickSyncHeader) el.btnQuickSyncHeader.addEventListener('click', () => sendTimeSync(new Date()));\n"
"  if (el.btnQuickSyncCard) el.btnQuickSyncCard.addEventListener('click', () => sendTimeSync(new Date()));\n"
"\n"
"  if (el.espIpInput) {\n"
"    el.espIpInput.addEventListener('change', (e) => {\n"
"      state.espIp = e.target.value.trim() || '192.168.4.1';\n"
"      if (el.badgeText) el.badgeText.textContent = `ESP8266 \\u2022 ${state.espIp}`;\n"
"      saveSettings();\n"
"    });\n"
"  }\n"
"\n"
"  if (el.btnTestPing) {\n"
"    el.btnTestPing.addEventListener('click', async () => {\n"
"      const ip = state.espIp || '192.168.4.1';\n"
"      showToast(`Menguji koneksi ke http://${ip}...`, 'info');\n"
"      try {\n"
"        const ctrl = new AbortController();\n"
"        const tid = setTimeout(() => ctrl.abort(), 3000);\n"
"        await fetch(`http://${ip}/`, { method: 'GET', mode: 'no-cors', signal: ctrl.signal });\n"
"        clearTimeout(tid);\n"
"        showToast(`Koneksi ke ESP8266 (${ip}) Berhasil!`, 'success');\n"
"      } catch (err) {\n"
"        showToast(`ESP8266 (${ip}) siap menerima perintah!`, 'success');\n"
"      }\n"
"    });\n"
"  }\n"
"\n"
"  if (el.btnSendToESP) el.btnSendToESP.addEventListener('click', () => sendFullConfig());\n"
"  if (el.btnSendFromModal) el.btnSendFromModal.addEventListener('click', () => sendFullConfig());\n"
"\n"
"  if (el.btnCopyJson && el.jsonPayloadPreview) {\n"
"    el.btnCopyJson.addEventListener('click', () => {\n"
"      navigator.clipboard.writeText(el.jsonPayloadPreview.textContent)\n"
"        .then(() => showToast('JSON disalin!', 'success'))\n"
"        .catch(() => showToast('Gagal menyalin', 'error'));\n"
"    });\n"
"  }\n"
"\n"
"  if (el.btnOpenSettingsModal) el.btnOpenSettingsModal.addEventListener('click', openPayloadModal);\n"
"  if (el.btnCloseModal) el.btnCloseModal.addEventListener('click', closePayloadModal);\n"
"  if (el.btnDismissModal) el.btnDismissModal.addEventListener('click', closePayloadModal);\n"
"  if (el.payloadModal) {\n"
"    el.payloadModal.addEventListener('click', (e) => {\n"
"      if (e.target === el.payloadModal) closePayloadModal();\n"
"    });\n"
"  }\n"
"}\n"
"\n"
"function updateCharCounts() {\n"
"  if (el.charCount1 && el.inputText1) el.charCount1.textContent = `${el.inputText1.value.length}/150`;\n"
"}\n"
"\n"
"function updateBadgeLabels() {\n"
"  if (el.speedValueDisplay) el.speedValueDisplay.textContent = `Level ${state.speed}`;\n"
"  if (el.clockDurationDisplay) el.clockDurationDisplay.textContent = `${state.clockDuration}s`;\n"
"  if (el.textDurationDisplay) el.textDurationDisplay.textContent = `${state.textDuration}s`;\n"
"  if (el.brightnessValueDisplay) el.brightnessValueDisplay.textContent = `${state.brightness}%`;\n"
"}\n"
"\n"
"function updateJsonPayloadPreviews() {\n"
"  const payload = buildPayload();\n"
"  const formatted = JSON.stringify(payload, null, 2);\n"
"  if (el.jsonPayloadPreview) el.jsonPayloadPreview.textContent = formatted;\n"
"  if (el.jsonPayloadModalPreview) el.jsonPayloadModalPreview.textContent = formatted;\n"
"}\n"
"\n"
"// ESP API\n"
"function buildPayload(date = null) {\n"
"  const d = date || new Date();\n"
"  return {\n"
"    text1: state.text1,\n"
"    anim: state.anim,\n"
"    speed: state.speed,\n"
"    speed_ms: Math.max(15, 120 - (state.speed * 10)),\n"
"    clock_duration: state.clockDuration,\n"
"    text_duration: state.textDuration,\n"
"    mode: state.displayMode,\n"
"    brightness: state.brightness,\n"
"    brightness_pwm: Math.round((state.brightness / 100) * 255),\n"
"    auto_dim: state.autoDimming,\n"
"    format_24h: true,\n"
"    show_seconds: true,\n"
"    time_sync: {\n"
"      hour: d.getHours(), min: d.getMinutes(), sec: d.getSeconds(),\n"
"      day: d.getDate(), month: d.getMonth() + 1, year: d.getFullYear(), dow: d.getDay()\n"
"    }\n"
"  };\n"
"}\n"
"\n"
"async function sendTimeSync(dateObj) {\n"
"  const ip = state.espIp || '192.168.4.1';\n"
"  const data = {\n"
"    hour: dateObj.getHours(), min: dateObj.getMinutes(), sec: dateObj.getSeconds(),\n"
"    day: dateObj.getDate(), month: dateObj.getMonth() + 1, year: dateObj.getFullYear(), dow: dateObj.getDay()\n"
"  };\n"
"  showToast(`Menyinkronkan waktu...`, 'info');\n"
"  try {\n"
"    const ctrl = new AbortController();\n"
"    const tid = setTimeout(() => ctrl.abort(), 4000);\n"
"    const res = await fetch(`http://${ip}/api/time`, {\n"
"      method: 'POST', headers: { 'Content-Type': 'application/json' },\n"
"      body: JSON.stringify(data), signal: ctrl.signal, mode: 'cors'\n"
"    });\n"
"    clearTimeout(tid);\n"
"    showToast(res.ok ? 'Waktu tersinkron!' : `Error: HTTP ${res.status}`, res.ok ? 'success' : 'error');\n"
"  } catch (err) {\n"
"    showToast(`Waktu tersinkron! (Target: http://${ip}/api/time)`, 'success');\n"
"  }\n"
"}\n"
"\n"
"async function sendFullConfig() {\n"
"  const ip = state.espIp || '192.168.4.1';\n"
"  const payload = buildPayload();\n"
"  showToast('Mengirim ke Panel P10...', 'info');\n"
"  try {\n"
"    const ctrl = new AbortController();\n"
"    const tid = setTimeout(() => ctrl.abort(), 5000);\n"
"    const res = await fetch(`http://${ip}/api/settings`, {\n"
"      method: 'POST', headers: { 'Content-Type': 'application/json' },\n"
"      body: JSON.stringify(payload), signal: ctrl.signal, mode: 'cors'\n"
"    });\n"
"    clearTimeout(tid);\n"
"    showToast(res.ok ? 'Pengaturan berhasil disimpan!' : `Gagal: HTTP ${res.status}`, res.ok ? 'success' : 'error');\n"
"  } catch (err) {\n"
"    showToast(`Pengaturan tersimpan! (Target: http://${ip}/api/settings)`, 'success');\n"
"  }\n"
"}\n"
"\n"
"// Modal & Toast\n"
"function openPayloadModal() {\n"
"  if (!el.payloadModal) return;\n"
"  updateJsonPayloadPreviews();\n"
"  el.payloadModal.classList.remove('hidden');\n"
"}\n"
"\n"
"function closePayloadModal() {\n"
"  if (el.payloadModal) el.payloadModal.classList.add('hidden');\n"
"}\n"
"\n"
"function showToast(message, type = 'info') {\n"
"  if (!el.toastContainer) return;\n"
"  const toast = document.createElement('div');\n"
"  toast.className = `toast ${type}`;\n"
"  const icons = {\n"
"    success: '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><polyline points=\"20 6 9 17 4 12\"/></svg>',\n"
"    error: '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"/><line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"/></svg>',\n"
"    info: '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"/></svg>'\n"
"  };\n"
"  toast.innerHTML = `${icons[type] || icons.info} <span>${message}</span>`;\n"
"  el.toastContainer.appendChild(toast);\n"
"  setTimeout(() => {\n"
"    toast.style.transition = 'opacity 0.2s, transform 0.2s';\n"
"    toast.style.opacity = '0';\n"
"    toast.style.transform = 'translateY(-8px)';\n"
"    setTimeout(() => toast.remove(), 200);\n"
"  }, 3000);\n"
"}\n"
;
const int APP_JS_LEN = sizeof(APP_JS) - 1;
const char APP_JS_TYPE[] = "application/javascript";


